version: "3.9"

services:
  db:
      image: postgres:15-alpine
      volumes:
        - postgres-db-volume:/var/lib/postgresql/data/
        
      ports:
      - 5432:5432
      expose:
        - 5432

      environment:
        - POSTGRES_USER=gbchallenge
        - POSTGRES_PASSWORD=gbchallenge12345
        - POSTGRES_DB=challenge
  app:
    build: ./src/
    container_name: fastapi
    restart: on-failure:10
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://gbchallenge:gbchallenge12345@db:5432/challenge
    depends_on:
      - db
    volumes:
      - ./src:/src

volumes:
  postgres-db-volume:

  